from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.colors import green, orange, red, black, HexColor
from reportlab.lib.utils import ImageReader
from math import cos, sin, radians
from datetime import datetime
import os


def generate_pdf_report(
    *,
    output_path: str,
    crack_percentage: float,
    risk_level: str,
    severity_score: float,
    annotated_image_path: str,
    heatmap_path: str,
    engineer_name: str,
    project_id: str
):
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4

    # ==================================================
    # DATE
    # ==================================================
    now = datetime.now()
    report_date = now.strftime("%d %B %Y | %I:%M %p")

    # ==================================================
    # RISK SETTINGS
    # ==================================================
    if risk_level == "Low":
        risk_color = green
        explanation = (
            "Low Risk: Minor surface-level cracks detected.\n"
            "No immediate structural concern. Routine monitoring advised."
        )
    elif risk_level == "Medium":
        risk_color = orange
        explanation = (
            "Medium Risk: Cracks may affect durability over time.\n"
            "Preventive repair and professional inspection recommended."
        )
    else:
        risk_color = red
        explanation = (
            "High Risk: Severe cracks detected.\n"
            "Structural integrity may be compromised. Immediate action required."
        )

    # ==================================================
    # PAGE 1 — SUMMARY
    # ==================================================
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 50, "StructScan AI – Structural Inspection Report")
    c.line(50, height - 60, width - 50, height - 60)

    c.setFont("Helvetica", 11)
    c.drawString(50, height - 95, f"Date: {report_date}")
    c.drawString(50, height - 120, f"Engineer: {engineer_name}")
    c.drawString(350, height - 120, f"Project ID: {project_id}")

    c.setFont("Helvetica", 12)
    c.drawString(50, height - 170, f"Crack Coverage: {crack_percentage:.2f}%")
    c.drawString(50, height - 200, f"Severity Score: {severity_score:.1f} / 100")
    c.drawString(50, height - 230, f"Risk Level: {risk_level}")

    # ==================================================
    # SEVERITY GAUGE (SPEEDOMETER)
    # ==================================================
    cx, cy = 300, height - 360
    radius = 90

    # Arc background
    c.setLineWidth(14)
    c.setStrokeColor(green)
    c.arc(cx - radius, cy - radius, cx + radius, cy + radius, 180, 120)

    c.setStrokeColor(orange)
    c.arc(cx - radius, cy - radius, cx + radius, cy + radius, 300, 120)

    c.setStrokeColor(red)
    c.arc(cx - radius, cy - radius, cx + radius, cy + radius, 60, 120)

    # Needle
    angle = 180 - (severity_score * 180 / 100)
    needle_x = cx + radius * 0.85 * cos(radians(angle))
    needle_y = cy + radius * 0.85 * sin(radians(angle))

    c.setStrokeColor(black)
    c.setLineWidth(2)
    c.line(cx, cy, needle_x, needle_y)
    c.circle(cx, cy, 5, fill=1)

    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(cx, cy - 110, "Severity Gauge")

    # ==================================================
    # RISK EXPLANATION
    # ==================================================
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, height - 480, "Risk Interpretation")

    c.setFont("Helvetica", 11)
    text = c.beginText(50, height - 510)
    for line in explanation.split("\n"):
        text.textLine(line)
    c.drawText(text)

    c.setFont("Helvetica", 9)
    c.drawString(50, 40, "Generated by StructScan AI")

    # ==================================================
    # PAGE 2 — ANNOTATED IMAGE
    # ==================================================
    if os.path.exists(annotated_image_path):
        c.showPage()
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 50, "Crack Detection – Bounding Boxes")

        img = ImageReader(annotated_image_path)
        c.drawImage(
            img,
            50,
            80,
            width=width - 100,
            height=height - 160,
            preserveAspectRatio=True
        )

        c.setFont("Helvetica", 9)
        c.drawString(50, 40, "StructScan AI – Detection Output")

    # ==================================================
    # PAGE 3 — HEATMAP
    # ==================================================
    if heatmap_path and os.path.exists(heatmap_path):
        c.showPage()
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 50, "Crack Density Heatmap")

        img = ImageReader(heatmap_path)
        c.drawImage(
            img,
            50,
            80,
            width=width - 100,
            height=height - 160,
            preserveAspectRatio=True
        )

        c.setFont("Helvetica", 9)
        c.drawString(50, 40, "Red areas indicate higher crack concentration")

    c.save()
    return output_path